apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: debug-container
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: debug
    spec:
      containers:
      - name: debug-container
        image: trainersontheweb/debug-container
