---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: debug
  namespace: default
spec:
  selector:
    matchLabels:
      app: debug 
  serviceName: "debug"
  replicas: 1
  template:
    metadata:
      labels:
        app: debug
    spec:
      containers:
      - name: debug-container
        image: qedzone/debug-container
